apiVersion: v1
kind: Service
metadata:
  name: checkout-api-svc
  namespace: cloudops
  labels:
    app: checkout-api
spec:
  type: ClusterIP
  selector:
    app: checkout-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
