apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checkout-api-ingress
  namespace: cloudops
spec:
  ingressClassName: nginx
  rules:
    - host: checkout.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: checkout-api-svc
                port:
                  number: 80
